_wandb:
    value:
        cli_version: 0.23.1
        e:
            y6it3fisdb5upgz5vue8kl611yldbde5:
                email: mhong@umn.edu
                executable: /home/zha00175/venv_verl/bin/python
                git:
                    commit: a6d3cb2cc77d2399775da3345ffe5cbbe2d3225b
                host: cs-u-converge
                os: Linux-5.15.0-134-generic-x86_64-with-glibc2.35
                program: <stdin>
                python: CPython 3.12.0
                root: /home/zha00175/mathscaffold
                startedAt: "2026-08-15T20:48:38.346508Z"
                writerId: y6it3fisdb5upgz5vue8kl611yldbde5
        m:
            - "1": ratio/frac_zero
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": cycle
              "6":
                - 3
              "7": []
            - "1": groups/all_fail
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": groups/frac_zero_grad
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": text/items
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": probe/math500
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": teacher/n_item_ops
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": ratio/mean
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": groups/mixed
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": state/graduated
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": text/p
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": ctrl/n_changes
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": probe/aime24
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": groups/all_pass
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": teacher/decision
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": teacher/n_tool_calls
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": teacher/n_ratio_ops
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": ratio/frac_ge50
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.0
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 7
                - 13
                - 14
            "4": 3.12.0
            "5": 0.23.1
            "10":
                - 20
            "12": 0.23.1
            "13": linux-x86_64
